# Generated by Django 4.2.6 on 2024-04-04 23:20


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_create_site_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=128)),
                ("text", models.TextField()),
                (
                    "recipients",

                    models.ManyToManyField(related_name="related_name_message", to=settings.AUTH_USER_MODEL),

                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.DeleteModel(
            name="SiteUser",
        ),
    ]
