# Generated by Django 4.2.7 on 2024-02-03 15:42

<<<<<<< HEAD
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_system", "0006_create_question_model"),
=======
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0006_create_question_model'),
>>>>>>> 5e6afde4c6d76c43252b22cb589861dd7611ff9a
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField(default=False)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testing_system.question")),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
=======
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
>>>>>>> 5e6afde4c6d76c43252b22cb589861dd7611ff9a
            },
        ),
    ]
