# Generated by Django 4.2.7 on 2024-02-10 18:39

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("testing_system", "0008_create_attempt_model"),
=======

    dependencies = [
        ('testing_system', '0008_create_attempt_model'),
>>>>>>> 5e6afde4c6d76c43252b22cb589861dd7611ff9a
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name="question",
            options={"verbose_name": "question", "verbose_name_plural": "questions"},
=======
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
>>>>>>> 5e6afde4c6d76c43252b22cb589861dd7611ff9a
        ),
    ]
